### ISSUE TITLE
Cannot pass credentials to the input when downloading EAP server

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-rsp-ui#23] opened 2019-07-11 09:09 UTC
Steps to reproduce:
1. Have RSP provider running in VSCode
2. Create new server -> RSP Server (eap, wf)
3. Download server -> YES 
4. Choose JBoss EAP server
5. Please provide your RH credentials: -> Continue... 
6. Insert your username and password
7. ASSERT: downloading of server starts and is successful
Actual result: I cannot provide the credentials as when I start typing the "Continue..." option disappears, same with password, I only can click continue and then I fail with "Your credentials have failed" - which also does not sounds right, should be ie., "Your credentials verification has failed".

**Comment by odockal** [comment] 2019-07-11 09:24
[object Object] was chosen
Message=Sending request 'server/downloadRuntime - (18)'. data=Params: {
    "requestId": null,
    "downloadRuntimeId": "jbosseap720runtime",
    "data": {}
}
Message=Received response 'server/downloadRuntime - (18)' in 1ms. data=Result: {
    "status": {
        "severity": 1,
        "plugin": "org.jboss.tools.rsp.server.spi",
        "code": 0,
        "message": "Please fill the requried information"
    },
    "requestId": 59592,
    "items": [
        {
            "id": "downloadmanager.credentials.label",
            "label": "Please provide your Red Hat credentials:",
            "responseType": "none",
            "responseSecret": false
        },
        {
            "id": "workflow.username",
            "label": "Username: ",
            "responseType": "string",
            "responseSecret": false
        },
        {
            "id": "workflow.password",
            "label": "Password: ",
            "responseType": "string",
            "responseSecret": true
        }
    ]
}

**Comment by lstocchi** [comment] 2019-07-11 09:34
Good catch @odockal .

It seems that the server returns this object 
![image](https://user-images.githubusercontent.com/49404737/61039655-76e83d00-a3cf-11e9-96fe-c29e5745c020.png)

but the UI expects this one:
```
interface WorkflowResponseItem {
        id: string;
        itemType: string;
        label: string;
        content: string;
        prompt: WorkflowPromptDetails;
        properties: {
            [index: string]: string;
        };
    }
```

This could also be the cause of the other problems related to the downloading process. Not sure if we're using an old version of rsp-server. I'll let you know asap.

**Comment by lstocchi** [comment] 2019-07-11 10:05
Solved. Wildfly/EAP Rsp Provider was using an old version of rsp-server (0.16.0, newest is 0.20.0).
Closing issue for the moment.

**Closed by lstocchi** 2019-07-11 10:05 UTC

**Comment by odockal** [comment] 2019-07-11 11:22
I confirm this. rsp server 0.20.0 made things work again.
