### ISSUE TITLE
WARNING: Failed to send notification message.

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-rsp-ui#115] opened 2020-07-08 16:35 UTC
1. Run VSCode instance
2. Start RSP provider
3. Run another VSCode instance
4. Start RSP again in second instance
5. Check for output in first instance

I got this:

```
Jul 08, 2020 6:31:56 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint notify
WARNING: Failed to send notification message.
org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.net.SocketException: Broken pipe (Write failed)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:72)
	at org.eclipse.lsp4j.jsonrpc.TracingMessageConsumer.consume(TracingMessageConsumer.java:91)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.notify(RemoteEndpoint.java:126)
	at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:88)
	at com.sun.proxy.$Proxy4.serverStateChanged(Unknown Source)
	at org.jboss.tools.rsp.server.model.RemoteEventManager.initClientWithServerStates(RemoteEventManager.java:101)
	at org.jboss.tools.rsp.server.ServerManagementServerImpl.clientAdded(ServerManagementServerImpl.java:121)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher.oneSocket(ServerManagementServerLauncher.java:158)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher.access$0(ServerManagementServerLauncher.java:140)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher$ListenOnSocketRunnable.run(ServerManagementServerLauncher.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:68)
	... 14 more
```

**Comment by robstryker** [comment] 2020-07-14 16:46
This will be fixed once we switch deps to the unreleased lsp4j libs.  For now it has to stay. 
Reference:  https://github.com/eclipse/lsp4j/pull/433#issuecomment-656318578

**Comment by robstryker** [comment] 2020-07-14 18:37
I'm closing this as a duplicate of https://github.com/redhat-developer/rsp-server/issues/584 

Since the fix will be in updating the rsp-server deps, and not in the UI, this bug is not with this component but with rsp-server.

**Closed by robstryker** 2020-07-14 18:37 UTC
