### ISSUE TITLE
Server status not correctly detected

### ISSUE THREAD

**Issue by lkachun9129** [redhat-developer/vscode-rsp-ui#167] opened 2021-03-18 03:13 UTC
I was using redhat.vscode-rsp-ui@0.23.7 with redhat.vscode-server-connector@0.23.10 via VSCode Remote SSH.

All servers claimed to be started after VSCode startup and were unable to be either stopped or terminated.

After fallback to redhat.vscode-rsp-ui@0.23.5 with redhat.vscode-server-connector@0.23.6, everything works fine again.

**Comment by robstryker** [comment] 2021-03-22 18:31
This is a duplicate of https://github.com/redhat-developer/vscode-rsp-ui/issues/159

**Closed by robstryker** 2021-03-22 18:31 UTC
