### ISSUE TITLE
Work with java 8

### ISSUE THREAD

**Issue by stimad** [redhat-developer/vscode-rsp-ui#129] opened 2020-07-27 08:57 UTC
Hello there.
I have project in java 8, and minimum java version that vscode requires now is 11. RSP uses that java version (11) to start application server (in my case wildlfy 17.1), but my project is not compatible with java 11 and I get errors. When I try to start Wildfly manually (with java 8) I don't get errors. My problem is directly related with MoldelMapper. Can I somehow use java 8 to run rsp? I have tried with vm.install.path in servers settings but I had got error that vm is not valid.

**Comment by lstocchi** [comment] 2020-07-27 09:00
Hello @stimad. We are aware of this error and we are working on a fix (https://github.com/redhat-developer/rsp-server/pull/590). Let you know when it will be released. Sorry for the inconvenience.

**Comment by stimad** [comment] 2020-07-27 09:19
> Hello @stimad. We are aware of this error and we are working on a fix ([redhat-developer/rsp-server#590](https://github.com/redhat-developer/rsp-server/pull/590)). Let you know when it will be released. Sorry for the inconvenience.

Thanks for quick response.

**Comment by stimad** [comment] 2020-07-27 11:48
Hi @lstocchi. I am not so experienced with vscode extensions. Can you please tell me how to fetch last changes from extension when it would be fixed? Do I have to wait next release or I can pull the latest code and build it somehow and make extension locally that I can implement in vscode?

**Comment by lstocchi** [comment] 2020-07-27 12:02
Hi @stimad, you just need to update your server connector extension and this will take care of using the latest rsp-server. No more from your side. I'll send you a message with the new version when it will be released.

In the meantime, if you want, you could downgrade the vscode-java extension and keep using java 8 as before.
Just go in the extension tab -> click on the settings wheel icon to the right of the `Language support for Java(TM) by Red Hat` -> install another version -> select the version you want. This way you should be ok until we release our fix, hopefully in few hours.

**Comment by stimad** [comment] 2020-07-27 12:15
Thank you @lstocchi 100 times. You saved my day 👍 . I taught that I would have to return to Eclipse until next release.

**Comment by lstocchi** [comment] 2020-07-27 12:16
@stimad you're welcome. For any issue, just write here ;)

**Comment by stimad** [comment] 2020-07-28 08:12
Hi @lstocchi, one more question. Did you consider to expand HCR, to work something like in Eclipse? I couldn't use it in Java enterprise apps with Wildfly. Did I do something wrong or hot reload still was not developed to work with this kind of applications?

**Comment by lstocchi** [comment] 2020-07-28 08:28
@stimad unfortunately i can't help on this and the person who work on the extension is PTO so he will be back in some weeks. I guess you can find more infos in the chat as another user asked something similar https://gitter.im/redhat-developer/server-connector?at=5d5acc574e17537f5261ea07 . If this doesn't answer your question, just write a message there and i'll ping someone more expert than me to reply :)

**Comment by lstocchi** [comment] 2020-07-28 09:59
@stimad the new server connector extension (0.23.3) was released so now you can use the latest vscode java ext. To make a single server use a different java.home, just right click to the server -> edit server -> add `"vm.install.path": "path/to/your/java8"` and save. Now it should work fine. Thank you and sorry for taking so long.

**Comment by stimad** [comment] 2020-07-28 10:08
No, thank you for fast assistance. I wish you good luck in future tasks and have to say that I really appreciate the job you guys do.

**Closed** 2020-07-30 15:06 UTC

**Comment by robstryker2** [comment] 2020-08-24 17:57
> Hi @lstocchi, one more question. Did you consider to expand HCR, to work something like in Eclipse? I couldn't use it in Java enterprise apps with Wildfly. Did I do something wrong or hot reload still was not developed to work with this kind of applications?

We have HCR support, but it's based on the vscode java debugger extension's abilities, which we can't control. While I haven't tested it lately, as I remember, it worked in the following way.  You can change a java file in your deployment as long as the debugger is not currently tracing through that code. The vscode java debugger extension will not allow you to change code that you are in the middle of debugging. This is different than how eclipse's HCR works, where when it notices a change, it restarts the method with the new code. 

Since this is a feature / functionality in the java debugger, it is out of our hands. But, if you're tracing code in a servlet, for example, you can just press play, allow the current request to be served, change your code, and initiate a new request that should hit your breakpoint. 

Again, I haven't tested this in a while, but I believe that was the major issue last time I checked.

**Comment by chouhy** [comment] 2023-04-15 06:58
This error appears again in v0.26.X.

**Comment by robstryker** [comment] 2023-04-18 17:21
Please post your server file where you declare the vm property.

**Comment by SkyGrass** [comment] 2023-05-11 01:06
`{
    "security.workspace.trust.untrustedFiles": "open",
    "git.openRepositoryInParentFolders": "never",
    "workbench.iconTheme": "material-icon-theme",
    "java.configuration.maven.globalSettings": "D:\\Java\\apache-maven-3.9.1\\conf\\settings.xml",
    "maven.executable.path": "D:\\Java\\apache-maven-3.9.1\\bin\\mvn",
    "files.associations": {
        "*.yml": "yaml"
    },
    "workbench.editorAssociations": {
        "*.yml": "default"
    },
    "rsp-ui.rsp.java.home": "D:\\Java\\jdk1.8.0_333",
    "rsp-ui.enableStartServerOnActivation": [
        {
            "id": "redhat.vscode-community-server-connector",
            "name": "Community Server Connector",
            "startOnActivation": true,
        }
    ]
}`

**Comment by robstryker** [comment] 2023-05-15 18:32
I'm sorry but this is not what a server file looks like, @SkyGrass 

A server file has properties similar to the following:

```
{
  "args.override.boolean": "false",
  "args.program.override.string": "some set of program arguments",
  "args.vm.override.string": "some set of vm-arguments",
  "id": "wf24",
  "id-set": "true",
  "org.jboss.tools.rsp.server.typeId": "org.jboss.ide.eclipse.as.wildfly.240",
  "server.autopublish.inactivity.limit": "2000",
  "server.home.dir": "/home/rob/apps/jboss/unzipped/wildfly-24.0.0.Final.zip.expanded",
  "server.timeout.shutdown": "120000",
  "server.timeout.startup": "120000",
  "wildfly.publish.restart.pattern": "\\.class$|\\.jar$"
}
```

This can be acquired by right-clicking on the server in the servers view and selecting `Edit Server` as shown: 
![image](https://github.com/redhat-developer/vscode-rsp-ui/assets/630383/f9df62e1-0ac7-46a3-88a0-0a66333e29a9)

**Comment by SkyGrass** [comment] 2023-05-15 18:32
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by robstryker** [comment] 2023-05-15 18:33
我看不懂中文。 有空时请用英文回复。

**Comment by SkyGrass** [comment] 2023-05-16 00:37
> 这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

This is an automated reply. I have received your email and will respond as soon as possible.

**Comment by fredngo** [comment] 2023-05-30 18:19
@robstryker Confirmed that v0.26.X has this problem again. Here's my server file:

```
{
  "args.override.boolean": "false",
  "args.program.override.string": "start",
  "args.vm.override.string": "-Djava.util.logging.config.file=/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -Dcatalina.base= -Dcatalina.home=/home/vagrant/tomcat/apache-tomcat-9.0.41 -Djava.io.tmpdir=/temp",
  "id": "Tomcat 9.x",
  "id-set": "true",
  "org.jboss.tools.rsp.server.typeId": "org.jboss.ide.eclipse.as.server.tomcat.90",
  "server.base.dir": "/home/vagrant/tomcat/apache-tomcat-9.0.41",
  "server.deploy.dir": "${server.base.dir}/webapps/",
  "server.home.dir": "/home/vagrant/tomcat/apache-tomcat-9.0.41",
  "server.http.host": "localhost",
  "server.http.port": "8080",
  "deployables": {
    "/home/vagrant/development/target/oscar": {
      "label": "/home/vagrant/development/target/oscar",
      "path": "/home/vagrant/development/target/oscar",
      "options": {}
    }
  }
}
```
