### ISSUE TITLE
RSP server provider not available right after extension installation in Server's activity bar

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-rsp-ui#94] opened 2020-01-08 13:30 UTC
Red Hat RSP Server root tree item is not available/visible when extension is installed under Servers bar. I have to open Explorer -> Servers tab first, it appeared there and then it is available under server activity bar.

**Comment by lstocchi** [comment] 2020-01-08 13:51
The problem is that the server connector is not updated (see my comment on the PR if you want to use an updated server connector https://github.com/redhat-developer/vscode-rsp-ui/pull/87#issuecomment-559721025). I was waiting for the activity bar PR to be merged. Didn't know you were testing it today. Update the server connector immediately.

**Comment by lstocchi** [comment] 2020-01-08 14:27
Done. It should be fixed by using the new server connector https://github.com/redhat-developer/vscode-server-connector/pull/415

**Comment by odockal** [comment] 2020-01-08 14:30
@lstocchi absolutely no problem, thanks!

**Comment by odockal** [comment] 2020-01-09 15:17
@lstocchi I can still reproduce the issue. Without switching to Explorer -> Servers the item 'Red Hat RSP server' is not present under servers view (the server activity bar). 

I would expect that when I install the extension (both of course) then I switch to Server's view I would get the item. Like opening the view triggers the element visibility to be turn on and simultaneously it should be starting...

**Comment by odockal** [comment] 2020-01-09 15:38
After little discussion with @lstocchi I have to admit that it seems to be working now. Issue was that the Code cached older version when reinstalling locally built vsix. Closing the editor solve the issue.

**Comment by lstocchi** [comment] 2020-02-19 14:05
@odockal closing it. If you still face a similar error feel free to reopen it

**Closed by lstocchi** 2020-02-19 14:05 UTC
Labels: bug
