### ISSUE TITLE
Extension backend error - rsp error - community server connector failed to start - typeerror: cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by ZXHHYJ** [redhat-developer/vscode-rsp-ui#252] opened 2022-11-04 19:42 UTC
jdk version is openjdk17.0.4

**Comment by robstryker** [comment] 2022-11-07 19:35
Duplicate of https://github.com/redhat-developer/vscode-server-connector/issues/557

**Closed by robstryker** 2022-11-07 19:35 UTC
