### ISSUE TITLE
RSP server provider seems to be not refreshing under Explorer -> Servers view

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-rsp-ui#106] opened 2020-03-20 13:08 UTC
I would like someone to check first, if this is real issue, or it is just on my side. When I operate and manipulate RSP server provider under its own activity bar, things seem to be behaving right. When I switch to explorer -> server view, rsp provider server item is not refreshing, when I, ie. stop it, label is not changed, even though the rsp is stopped. So I still get full batch of action I can perform over it, like stop, which throw error pop up. 

I am using server-connector and rsp-ui built locally from actual master, that's why I ask also for cooperation here. I was playing with rsp server for a while, things were ok, until I tried to download crc which did not appear under rsp server (in explorer -> servers view). But it is created under Servers activity bar.

**Comment by odockal** [comment] 2020-03-20 13:09
AAaaaand, rsp provider got broken under its activity view as well... strange..

**Comment by lstocchi** [comment] 2020-03-20 13:18
@odockal i'm giving a look. Just to clarify. It works fine until you downloaded crc? After that it stopped working as expected?

**Comment by odockal** [comment] 2020-03-20 13:20
@lstocchi I am not saying that it was the exact event which break stuff, it might be just a hint.

**Comment by lstocchi** [comment] 2020-03-20 14:11
@odockal i tried everything it came to my mind but i didn't have any issue for now. Let's keep this open. I'll try to play with it in the next days to see if i discover something. I don't know if you already checked it but there was something in the Toggle Developer Tools's console?

**Comment by odockal** [comment] 2020-03-20 14:14
@lstocchi Nothing noticeable there. But it seems that what you do in servers activity bar is not mirrored into explorer -> servers tab...

**Comment by odockal** [comment] 2020-03-26 21:45
@lstocchi @robstryker  I played today with latest adapters suite (server-connector + rsp-ui) and after some time of debugging it happened again. This time it is bit different. I was debugging wf 19, server started, deployment added, etc. I finished and wanted to check eap 7.3 server, so I stopped wf 19 and started eap 7.3. Now, wf 19 was still started and eap 7.3 stopped, this was happening under explorer, servers tab, while under Servers activity bar, server items were marked started/stopped correctly. It seems some tree refreshing is misbehaving in explorer view. Or vscode is somehow changing tree item ids, so we got it wrong in that tab... not sure.

**Comment by lstocchi** [comment] 2020-03-27 08:40
:( ... @odockal my first thought is that this PR created this bug https://github.com/redhat-developer/vscode-rsp-ui/pull/100 . I'll give it a look but we can also make some tests by removing it. If this is not the cause of the issue i don't have any clue what it could be.

**Comment by robstryker** [comment] 2020-03-30 19:58
I played around with this endlessly and can't replicate it.

**Comment by odockal** [comment] 2020-04-01 09:43
I probably found the root cause. Try to install/uninstall some extension so that you have to "reload" the vscode. After that, I was able to find discrepancies among servers in their states under explorer bar and server bar.

**Comment by odockal** [comment] 2020-04-01 10:24
So to reproduce:
1. Start vscode
2. Install adapters (rsp-ui and server-connector)
3. Start RSP provider
4. Create two random servers (I choose eap 7.3 and wildfly 19)
5. Start one of them. 
6. Assert: Servers are present and shows correct states in both views (servers activity bar and explorer's server tab, for now on referenced as Servers bar and tab)
7. You can check that now any state change or operation performed on the server is nicely behaving in both bar and tab.
8. Option A -> Install/uninstall extension  so that you have to click "reload required"
8. Option B -> Exit and start over vscode
9. Wait for rsp to be started again
10. Assert: RSP is started over
11. Assert: servers and their states are the same in both bar and tab
12. Change state of some server in servers bar 
13. Assert: changes are propagated into servers tab
Actual result: now the state update fails and information are not synchronized anymore.

I am now trying this with @lstocchi PR #108 - branch i106. Though, I do not get previously receiver errors but rather simple rsp errors, like:
```
notificationsAlerts.ts:40 Unable to terminate the server:  Extension backend error - the server is already stopped.
onDidChangeNotification @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:587
addNotification @ notifications.ts:183
notify @ notificationService.ts:101
(anonymous) @ mainThreadMessageService.ts:83
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
```

**Comment by robstryker** [comment] 2020-10-05 20:28
Closing as out of date since we removed the activity bar

**Closed by robstryker** 2020-10-05 20:28 UTC
